#thisworks

name: Auto Merge

on:
  pull_request:
    branches:
      - IntMeow
    types: [ closed ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge IntMeow to TestMeow
        run: |
            git config --global user.email "ndondzila@gmail.com"
            git config --global user.name "nick"
            git config pull.rebase false
            git fetch origin
            git push -u origin TestMeow
