# test number 2

name: Auto Merge

on:
  pull_request:
    types: [ closed ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge IntMeow to TestMeow
        run: |
            git git ls-remote
    ###      git checkout refs/remotes/origin/TestMeow
    ###      git pull origin refs/remotes/origin/IntMeow

   ###   - name: Merge Test to Stage
   ###     run: |
   ###        git checkout "StageMeow"
   ###        git pull origin "TestMeow"
