# test number 2

name: Auto Merge

on:
  pull_request:
    branches:
      - IntMeow
    types: [ closed ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge IntMeow to TestMeow
        run: |
            git fetch origin
            git config pull.rebase false
            git checkout TestMeow
            git pull origin IntMeow -f
            git push remote origin

   ###   - name: Merge Test to Stage
   ###     run: |
   ###        git checkout "StageMeow"
   ###        git pull origin "TestMeow"
