#thisworks

name: Auto Merge

on:
  pull_request:
    branches:
      - IntMeow
    types: [ closed ]

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge Int -> Test
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: IntMeow
          target_branch: TestMeow
